using Blake.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Reflection;
using Xunit;

namespace Blake.SourceGenerator.Tests;

public class AssemblyEnumerationTests
{
    [Fact]
    public void FindTypesImplementing_FindsAllImplementations()
    {
        // Arrange - Create a Blake source that uses FindTypesImplementing
        var blakeSource = @"namespace TestApp;

public class TestComposition
{
@{|
    var types = Blake.FindTypesImplementing(""TestAssemblyA.InterfaceA"");
    foreach (var type in types)
    {
        var propName = type.Name;
`   public @(type.ToDisplayString()) @(propName) { get; set; }`
    }
|}
}
";

        // Create a compilation that includes TestAssemblyA and TestAssemblyB
        var compilation = CreateTestCompilation();

        // Act - Parse and interpret the Blake source
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake", compilation);
        var output = interpreter.Expand(ast);

        // Expected output
        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace TestApp;

public class TestComposition
{
    public TestAssemblyA.TestAssemblyATypeA TestAssemblyATypeA { get; set; }
    public TestAssemblyA.TestAssemblyATypeB TestAssemblyATypeB { get; set; }
    public TestAssemblyB.TestAssemblyBTypeA TestAssemblyBTypeA { get; set; }
}
";

        // Assert - Verify exact output
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    /// <summary>
    /// Creates a CSharpCompilation that includes TestAssemblyA and TestAssemblyB as metadata references.
    /// </summary>
    private static CSharpCompilation CreateTestCompilation()
    {
        // Get the locations of the test assemblies
        var testAssemblyALocation = typeof(TestAssemblyA.InterfaceA).Assembly.Location;
        var testAssemblyBLocation = typeof(TestAssemblyB.TestAssemblyBTypeA).Assembly.Location;

        // Add all loaded assemblies as references to ensure runtime types are available
        var referencesList = new List<MetadataReference>();

        // Add core references
        referencesList.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));
        referencesList.Add(MetadataReference.CreateFromFile(testAssemblyALocation));
        referencesList.Add(MetadataReference.CreateFromFile(testAssemblyBLocation));

        // Add all other loaded assemblies to provide full runtime context
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (!string.IsNullOrEmpty(asm.Location) &&
                asm != typeof(object).Assembly &&
                !asm.Location.Contains("TestAssemblyA") &&
                !asm.Location.Contains("TestAssemblyB"))
            {
                try
                {
                    referencesList.Add(MetadataReference.CreateFromFile(asm.Location));
                }
                catch
                {
                    // Skip assemblies that can't be referenced
                }
            }
        }

        // Create a minimal compilation
        var compilation = CSharpCompilation.Create(
            assemblyName: "TestCompilation",
            syntaxTrees: null,
            references: referencesList,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        return compilation;
    }
}
