using Blake.SourceGenerator;
using Xunit;

namespace Blake.SourceGenerator.Tests;

public class BasicGenerationTests
{
    [Fact]
    public void SimpleProperty_GeneratesCorrectly()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public partial class User
{
@{|
    var name = ""FirstName"";
    var type = ""string"";
`   public @(type) @(name) { get; set; }`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public partial class User
{
    public string FirstName { get; set; }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert - normalize by removing the timestamp line
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void NoLeadingWhitespace_PreservesSpacing()
    {
        var blakeSource = @"namespace MyApp;

public partial class User
{
    public @{|`string Greeting`|} { get; set; }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public partial class User
{
    public string Greeting { get; set; }
}
";

        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void MultilineQuasiQuote_GeneratesCorrectly()
    {
        var blakeSource = @"namespace MyApp;

public class MyClass
{
@{|
    var className = ""Person"";
`   public class @(className)
    {
        public int Id { get; set; }
    }`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class MyClass
{
    public class Person
    {
        public int Id { get; set; }
    }
}
";

        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void ReadmeExample_GeneratesCorrectly()
    {
        var blakeSource = @"namespace MyApp.Models;

public partial class User
{
    public int Id { get; set; }

@{|
    // This C# code runs at compile time
    var fields = new[]
    {
        (""FirstName"", ""string""),
        (""LastName"", ""string""),
        (""Email"", ""string""),
        (""Age"", ""int?""),
    };

    foreach (var (name, type) in fields)
    {
        // Backtick strings are OUTPUT - they emit to the generated file
        // @(expr) splices in the compile-time value
        // Newline is implicit after the closing backtick
`   public @(type) @(name) { get; set; }`
    }
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public int? Age { get; set; }
}
";

        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }
}
