using Xunit;

namespace Blake.SourceGenerator.Tests;

/// <summary>
/// Tests for shared context between meta-blocks within a single file.
/// Variables declared in one @{| |} block should be accessible in subsequent blocks.
/// </summary>
public class SharedContextTests
{
    private static string GenerateBlakeCode(string blakeSource)
    {
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();
        var interpreter = new BlakeInterpreter("test.blake");
        return interpreter.Expand(ast);
    }

    [Fact]
    public void SharedVariable_DeclaredInFirstBlock_UsableInSecondBlock()
    {
        var blakeCode = @"namespace Test;

public class SharedContextDemo
{
@{|
    var greeting = ""Hello"";
    `   public string Message1 => ""@(greeting)"";`
|}

@{|
    // greeting should still be in scope from previous block
    `   public string Message2 => ""@(greeting) World"";`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class SharedContextDemo
{
    public string Message1 => ""Hello"";

    public string Message2 => ""Hello World"";
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void SharedArray_DeclaredOnce_UsedMultipleTimes()
    {
        var blakeCode = @"namespace Test;

public class User
{
@{|
    var schema = new[] {
        new { Name = ""Id"", Type = ""int"" },
        new { Name = ""Username"", Type = ""string"" },
        new { Name = ""Email"", Type = ""string"" }
    };
|}

@{|
    // Use schema for properties
    foreach (var field in schema) {
        `   public @(field.Type) @(field.Name) { get; set; }`
    }
|}

@{|
    // Use schema again for a method
    `   public void Validate() {`
    foreach (var field in schema) {
        `       // Validate @(field.Name)`
    }
    `   }`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class User
{

    public int Id { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }

    public void Validate() {
        // Validate Id
        // Validate Username
        // Validate Email
    }
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void SharedCounter_IncrementedAcrossBlocks()
    {
        var blakeCode = @"namespace Test;

public class Counter
{
@{|
    var count = 0;
    `   public const int First = @(count++);`
|}

@{|
    `   public const int Second = @(count++);`
|}

@{|
    `   public const int Third = @(count++);`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class Counter
{
    public const int First = 0;

    public const int Second = 1;

    public const int Third = 2;
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void SharedList_BuildUpAcrossBlocks()
    {
        var blakeCode = @"namespace Test;

public class ListBuilder
{
@{|
    var items = new System.Collections.Generic.List<string>();
    items.Add(""First"");
|}

@{|
    items.Add(""Second"");
|}

@{|
    items.Add(""Third"");
    foreach (var item in items) {
        `   public string Get@(item)() => ""@(item)"";`
    }
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class ListBuilder
{


    public string GetFirst() => ""First"";
    public string GetSecond() => ""Second"";
    public string GetThird() => ""Third"";
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void ComplexSharedState_MultipleVariables()
    {
        var blakeCode = @"namespace Test;

public class ComplexState
{
@{|
    var name = ""MyClass"";
    var version = 1;
    var features = new[] { ""Feature1"", ""Feature2"" };
|}

@{|
    `   public string Name => ""@(name)"";`
    `   public int Version => @(version);`
|}

@{|
    foreach (var feature in features) {
        `   public bool Has@(feature) => true;`
    }
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class ComplexState
{

    public string Name => ""MyClass"";
    public int Version => 1;

    public bool HasFeature1 => true;
    public bool HasFeature2 => true;
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void LocalFunctions_SharedAcrossBlocks()
    {
        var blakeCode = @"namespace Test;

public class LocalFunctionSharing
{
@{|
    string Capitalize(string s) => char.ToUpper(s[0]) + s.Substring(1);
    var words = new[] { ""hello"", ""world"" };
|}

@{|
    foreach (var word in words) {
        `   public string Get@(Capitalize(word))() => ""@(Capitalize(word))"";`
    }
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace Test;

public class LocalFunctionSharing
{

    public string GetHello() => ""Hello"";
    public string GetWorld() => ""World"";
}
";

        var generated = GenerateBlakeCode(blakeCode);

        var outputNormalized = TestHelpers.NormalizeOutput(generated);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }
}
