using Blake.SourceGenerator;
using Xunit;

namespace Blake.SourceGenerator.Tests;

public class VarReturnTypeTests
{
    [Fact]
    public void SimpleVarReturnType_InfersString()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetName() { return ""Blake""; }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public string GetName() { return ""Blake""; }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void VarReturnType_InfersInt()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetValue() { return 42; }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public int GetValue() { return 42; }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void ExpressionBodiedVar_InfersType()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetValue() => 42;
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public int GetValue() => 42;
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void NoReturnStatements_InfersVoid()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var DoNothing() { }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public void DoNothing() { }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void AsyncVarReturnType_InfersTaskOfString()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

using System.Threading.Tasks;

public class Test
{
    public async var GetNameAsync()
    {
        await Task.Delay(1);
        return ""Blake"";
    }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

using System.Threading.Tasks;

public class Test
{
    public async Task<string> GetNameAsync()
    {
        await Task.Delay(1);
        return ""Blake"";
    }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void AsyncVarWithNoReturn_InfersTask()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

using System.Threading.Tasks;

public class Test
{
    public async var DoWorkAsync()
    {
        await Task.Delay(1);
    }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

using System.Threading.Tasks;

public class Test
{
    public async Task DoWorkAsync()
    {
        await Task.Delay(1);
    }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void LocalFunctionWithVar_InfersType()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public void Outer()
    {
        var Inner() { return 42; }
        int x = Inner();
    }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public void Outer()
    {
        int Inner() { return 42; }
        int x = Inner();
    }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void MultipleReturnsSameType_InfersCorrectly()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetMessage(bool happy)
    {
        if (happy)
            return ""Yay!"";
        return ""Boo!"";
    }
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public string GetMessage(bool happy)
    {
        if (happy)
            return ""Yay!"";
        return ""Boo!"";
    }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void VarReturnType_WithMetaBlocks()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
@{|
    var propName = ""Name"";
`   public var Get@(propName)() { return ""Blake""; }`
|}
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public string GetName() { return ""Blake""; }
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void MultipleReturnsDifferentTypes_ThrowsError()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetValue(bool useString)
    {
        if (useString)
            return ""text"";
        return 42;
    }
}
";

        // Act & Assert
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");

        var exception = Assert.Throws<BlakeExecutionException>(() => interpreter.Expand(ast));
        Assert.Contains("conflicting types", exception.Message);
        Assert.Contains("string", exception.Message);
        Assert.Contains("int", exception.Message);
    }

    [Fact]
    public void StaticVarReturnType_InfersCorrectly()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    public static var GetValue() => 123;
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    public static int GetValue() => 123;
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void PrivateVarReturnType_InfersCorrectly()
    {
        // Arrange
        var blakeSource = @"namespace MyApp;

public class Test
{
    private var GetSecret() => ""secret"";
}
";

        var expected = @"// <auto-generated>
// Generated from: test.blake
// Generated at: TIMESTAMP
// </auto-generated>

namespace MyApp;

public class Test
{
    private string GetSecret() => ""secret"";
}
";

        // Act
        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // Assert
        var outputNormalized = TestHelpers.NormalizeOutput(output);
        var expectedNormalized = TestHelpers.NormalizeOutput(expected);

        Assert.Equal(expectedNormalized, outputNormalized);
    }

    [Fact]
    public void TransformationIsActuallyRun_DebugTest()
    {
        // This test verifies that our transformation pipeline is actually being called
        var blakeSource = @"namespace MyApp;

public class Test
{
    public var GetValue() => 42;
}
";

        var parser = new BlakeParser(blakeSource, "test.blake");
        var ast = parser.Parse();

        var interpreter = new BlakeInterpreter("test.blake");
        var output = interpreter.Expand(ast);

        // The output should NOT contain "var" as a return type
        Assert.DoesNotContain("public var GetValue", output);
        // It SHOULD contain the inferred type
        Assert.Contains("public int GetValue", output);
    }
}
