using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Emit;
using Blake.SourceGenerator.Interpreter;

namespace Blake.SourceGenerator;

/// <summary>
/// Executes meta-blocks and expands quasi-quotes in a Blake AST.
///
/// The interpreter:
/// 1. Passes through C# code unchanged
/// 2. Executes meta-block code at compile time using Roslyn compilation
/// 3. Expands quasi-quotes (`...`) by evaluating splices @(expr) and emitting output
/// </summary>
public class BlakeInterpreter
{
    private readonly string _filePath;
    private readonly Compilation? _compilation;
    private int _blockCounter = 0;

    // Cache the compiled Blake API assembly to avoid recompiling for every meta-block
    private byte[]? _blakeApiAssemblyBytes;
    private Assembly? _blakeApiAssembly;
    private readonly object _blakeApiLock = new object();
    private bool _assemblyResolveHooked = false;

    public BlakeInterpreter(string filePath, Compilation? compilation = null)
    {
        _filePath = filePath;
        _compilation = compilation;

        // Hook AssemblyResolve to provide Blake.Runtime when needed
        if (!_assemblyResolveHooked)
        {
            AppDomain.CurrentDomain.AssemblyResolve += OnAssemblyResolve;
            _assemblyResolveHooked = true;
        }
    }

    private Assembly? OnAssemblyResolve(object? sender, ResolveEventArgs args)
    {
        // If requesting Blake.Runtime assembly and we have it cached, return it
        // Check against the cached assembly's full name to be precise
        if (_blakeApiAssembly != null && args.Name == _blakeApiAssembly.FullName)
        {
            return _blakeApiAssembly;
        }
        return null;
    }

    /// <summary>
    /// Expands the Blake AST into C# source code.
    /// </summary>
    public string Expand(BlakeFile file)
    {
        var output = new StringBuilder();
        output.AppendLine("// <auto-generated>");
        output.AppendLine($"// Generated from: {Path.GetFileName(file.FilePath)}");
        output.AppendLine($"// Generated at: {DateTime.UtcNow:O}");
        output.AppendLine("// </auto-generated>");
        output.AppendLine();

        // Collect all meta-blocks from the file
        var metaBlocks = file.Children.OfType<MetaBlock>().ToList();

        // Execute all meta-blocks together to share context within the file
        var metaBlockOutputs = metaBlocks.Count > 0
            ? CompileAndExecuteAllMetaBlocks(metaBlocks)
            : new string[0];

        // Track which meta-block we're on
        int metaBlockIndex = 0;

        foreach (var node in file.Children)
        {
            // Emit line mapping comment for LSP hover support
            // Skip for inline code to avoid breaking inline statements
            bool shouldEmitLineComment = true;

            if (node is MetaBlock metaBlock)
            {
                // If all quasi-quotes are inline, this is an inline meta-block
                shouldEmitLineComment = !metaBlock.QuasiQuotes.All(qq => qq.IsInline);
            }
            else if (node is CSharpPassthrough)
            {
                // Skip line comment for passthrough nodes that don't start on a new line
                // (i.e., they're part of an inline statement)
                if (output.Length > 0 && output[output.Length - 1] != '\n')
                {
                    shouldEmitLineComment = false;
                }
            }

            if (shouldEmitLineComment)
            {
                // Ensure we're on a new line first, then add the comment
                if (output.Length > 0 && output[output.Length - 1] != '\n')
                {
                    output.AppendLine();
                }
                output.AppendLine($"// #blake-line {node.Line}");
            }

            switch (node)
            {
                case CSharpPassthrough passthrough:
                    // C# code outside meta-blocks passes through unchanged
                    output.Append(passthrough.Code);
                    break;

                case MetaBlock mb:
                    // Use pre-computed output from shared context execution
                    output.Append(metaBlockOutputs[metaBlockIndex++]);
                    break;
            }
        }

        var expandedCode = output.ToString();

        // Apply transformations to the complete output
        return ApplyTransformations(expandedCode);
    }

    /// <summary>
    /// Gets the compilation references needed for meta-block execution.
    /// Includes references from the target compilation and runtime assemblies.
    /// </summary>
    private List<MetadataReference> GetCompilationReferences()
    {
        var references = new List<MetadataReference>();
        var referencePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Helper to add reference without duplicates
        void AddReference(string path)
        {
            if (!string.IsNullOrEmpty(path) && referencePaths.Add(path))
            {
                try
                {
                    references.Add(PortableExecutableReference.CreateFromFile(path));
                }
                catch (Exception ex)
                {
                    throw new BlakeExecutionException(
                        $"Error creating PortableExecutableReference from file '{path}': {ex.GetType().Name}: {ex.Message}",
                        ex);
                }
            }
        }

        // Add Microsoft.CodeAnalysis.dll reference for the embedded Blake API
        Assembly? codeAnalysisAssembly = null;
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            try
            {
                if (asm.GetName().Name == "Microsoft.CodeAnalysis")
                {
                    codeAnalysisAssembly = asm;
                    break;
                }
            }
            catch (NotSupportedException)
            {
                // Dynamic or collectible assemblies don't support GetName()
                continue;
            }
        }

        if (codeAnalysisAssembly != null && !string.IsNullOrEmpty(codeAnalysisAssembly.Location))
        {
            AddReference(codeAnalysisAssembly.Location);
        }
        else
        {
            throw new BlakeExecutionException(
                $"Microsoft.CodeAnalysis.dll not found in loaded assemblies or has empty Location",
                null);
        }

        // Add references from the compilation - these are the authoritative references for the target app
        if (_compilation != null)
        {
            foreach (var reference in _compilation.References)
            {
                if (reference is PortableExecutableReference portableRef && !string.IsNullOrEmpty(portableRef.FilePath))
                {
                    // Filter out specific assemblies that have namespace conflicts with Blake.Runtime
                    var fileName = Path.GetFileNameWithoutExtension(portableRef.FilePath);
                    if (fileName != null &&
                        fileName != "Blake.SourceGenerator" &&
                        fileName != "Blake.SourceGenerator.Tests")
                    {
                        AddReference(portableRef.FilePath);
                    }
                }
            }
        }
        else
        {
            // When no compilation context (e.g., unit tests), add all runtime assemblies from AppDomain
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    var name = asm.GetName().Name;
                    // Skip specific assemblies that would cause conflicts or that we handle explicitly
                    if (name != null &&
                        !name.StartsWith("Microsoft.CodeAnalysis") &&
                        name != "Blake.SourceGenerator" &&
                        name != "Blake.SourceGenerator.Tests" &&
                        name != "Blake.Runtime" &&
                        !string.IsNullOrEmpty(asm.Location))
                    {
                        AddReference(asm.Location);
                    }
                }
                catch (NotSupportedException)
                {
                    // Dynamic or collectible assemblies don't support GetName()
                    continue;
                }
            }
        }

        // Add netstandard if available
        try
        {
            var runtimePath = Path.GetDirectoryName(typeof(object).Assembly.Location);
            if (runtimePath != null)
            {
                var dotnetRoot = Path.GetDirectoryName(Path.GetDirectoryName(runtimePath));
                if (dotnetRoot != null)
                {
                    var netstandardRefPath = Path.Combine(dotnetRoot, "packs", "NETStandard.Library.Ref");
                    if (Directory.Exists(netstandardRefPath))
                    {
                        var versions = Directory.GetDirectories(netstandardRefPath)
                            .Select(d => Path.GetFileName(d))
                            .OrderByDescending(v => v)
                            .FirstOrDefault();

                        if (versions != null)
                        {
                            var netstandardDll = Path.Combine(netstandardRefPath, versions, "ref", "netstandard2.0", "netstandard.dll");
                            AddReference(netstandardDll);
                        }
                    }
                }
            }
        }
        catch (DirectoryNotFoundException)
        {
            // netstandard directory not found - compilation references should be sufficient
        }
        catch (UnauthorizedAccessException)
        {
            // No access to netstandard directory - compilation references should be sufficient
        }

        return references;
    }

    /// <summary>
    /// Compiles and executes all meta-blocks from a file in a shared context.
    /// Variables declared in one meta-block are accessible in subsequent blocks within the same file.
    /// </summary>
    private string[] CompileAndExecuteAllMetaBlocks(List<MetaBlock> metaBlocks)
    {
        if (metaBlocks.Count == 0)
            return new string[0];

        try
        {
            var className = $"BlakeMetaBlock_{_blockCounter++}";

            // Build combined code that executes all meta-blocks in sequence
            var codeBuilder = new StringBuilder();
            codeBuilder.AppendLine("        var outputs = new System.Collections.Generic.List<string>();");
            codeBuilder.AppendLine("        var __output = new System.Text.StringBuilder();");
            codeBuilder.AppendLine();

            for (int i = 0; i < metaBlocks.Count; i++)
            {
                var metaBlock = metaBlocks[i];
                var code = metaBlock.Code;

                // Replace quasi-quote placeholders for this meta-block
                for (int j = metaBlock.QuasiQuotes.Count - 1; j >= 0; j--)
                {
                    var qq = metaBlock.QuasiQuotes[j];
                    var interpolatedString = BuildInterpolatedString(qq);
                    var replacement = $"__output.Append({interpolatedString});";
                    code = code.Replace($"__emit_{j}__();", replacement);
                }

                codeBuilder.AppendLine($"        // Meta-block {i} (line {metaBlock.Line})");

                // Indent each line of the meta-block code
                foreach (var line in code.Split('\n'))
                {
                    codeBuilder.AppendLine("        " + line.TrimEnd('\r'));
                }

                codeBuilder.AppendLine("        outputs.Add(__output.ToString());");
                codeBuilder.AppendLine("        __output.Clear();");
                codeBuilder.AppendLine();
            }

            codeBuilder.AppendLine("        return outputs.ToArray();");

            // Build wrapper that executes all blocks in shared context
            var wrappedCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Microsoft.CodeAnalysis;

public static class {className}
{{
    public static string[] Execute(Compilation? providedCompilation)
    {{
        Blake.Initialize(providedCompilation);

{codeBuilder}
    }}
}}
";

            // Create syntax tree
            var syntaxTree = CSharpSyntaxTree.ParseText(wrappedCode);

            // Get references (same as CompileAndExecute)
            var references = GetCompilationReferences();

            // Compile Blake API once and add as reference
            EnsureBlakeApiCompiled(references);
            if (_blakeApiAssemblyBytes != null)
            {
                references.Add(MetadataReference.CreateFromImage(_blakeApiAssemblyBytes));
            }

            // Create compilation
            var compilation = CSharpCompilation.Create(
                assemblyName: className,
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            // Check for compilation errors
            var diagnostics = compilation.GetDiagnostics();
            var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
            if (errors.Any())
            {
                var errorMessages = string.Join("\n", errors.Select(e => e.ToString()));
                var firstBlockLine = metaBlocks[0].Line;
                throw new BlakeExecutionException(
                    $"Compilation error in meta-blocks starting at line {firstBlockLine}:\n{errorMessages}",
                    null);
            }

            // Emit to memory
            using var ms = new MemoryStream();
            var emitResult = compilation.Emit(ms);

            if (!emitResult.Success)
            {
                var failures = emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error);
                var errorMessages = string.Join("\n", failures.Select(f => f.ToString()));
                var firstBlockLine = metaBlocks[0].Line;
                throw new BlakeExecutionException(
                    $"Emit error in meta-blocks starting at line {firstBlockLine}:\n{errorMessages}",
                    null);
            }

            // Load and execute
            ms.Seek(0, SeekOrigin.Begin);
            var assembly = Assembly.Load(ms.ToArray());
            var type = assembly.GetType(className);
            var method = type?.GetMethod("Execute", BindingFlags.Public | BindingFlags.Static);

            if (method == null)
            {
                throw new BlakeExecutionException(
                    $"Could not find Execute method in generated assembly",
                    null);
            }

            var result = method.Invoke(null, new object?[] { _compilation });
            return (string[])result!;
        }
        catch (Exception ex) when (ex is not BlakeExecutionException)
        {
            var firstBlockLine = metaBlocks[0].Line;
            throw new BlakeExecutionException(
                $"Error executing meta-blocks starting at line {firstBlockLine}: {ex.Message}",
                ex);
        }
    }

    /// <summary>
    /// Compiles the Blake API once and caches it for reuse across all meta-blocks.
    /// </summary>
    private void EnsureBlakeApiCompiled(List<MetadataReference> references)
    {
        if (_blakeApiAssembly != null)
            return;

        lock (_blakeApiLock)
        {
            if (_blakeApiAssembly != null)
                return;

            // Load Blake API template from embedded resource
            var blakeApiCode = LoadEmbeddedResource("Blake.SourceGenerator.BlakeAPITemplate.cs");

            // Wrap in usings
            var wrappedApiCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Microsoft.CodeAnalysis;

{blakeApiCode}
";

            // Compile Blake API into a separate assembly
            var syntaxTree = CSharpSyntaxTree.ParseText(wrappedApiCode);
            var compilation = CSharpCompilation.Create(
                assemblyName: "Blake.Runtime",
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            // Check for compilation errors
            var diagnostics = compilation.GetDiagnostics();
            var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
            if (errors.Any())
            {
                var errorMessages = string.Join("\n", errors.Select(e => e.ToString()));
                throw new BlakeExecutionException(
                    $"Blake API compilation error:\n{errorMessages}",
                    null);
            }

            // Emit to memory
            using var ms = new MemoryStream();
            var emitResult = compilation.Emit(ms);

            if (!emitResult.Success)
            {
                var failures = emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error);
                var errorMessages = string.Join("\n", failures.Select(f => f.ToString()));
                throw new BlakeExecutionException(
                    $"Blake API emit error:\n{errorMessages}",
                    null);
            }

            _blakeApiAssemblyBytes = ms.ToArray();

            // Load the assembly so it's available for resolution
            _blakeApiAssembly = Assembly.Load(_blakeApiAssemblyBytes);
        }
    }

    /// <summary>
    /// Compiles and executes meta-block code using Roslyn compilation.
    /// </summary>
    private string CompileAndExecute(string code, int line)
    {
        var className = $"BlakeMetaBlock_{_blockCounter++}";

        // Build wrapper that references the pre-compiled Blake API
        var wrappedCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Microsoft.CodeAnalysis;

public static class {className}
{{
    public static string Execute(Compilation? providedCompilation)
    {{
        Blake.Initialize(providedCompilation);
        var __output = new StringBuilder();

{code}

        return __output.ToString();
    }}
}}
";

        // Create syntax tree
        var syntaxTree = CSharpSyntaxTree.ParseText(wrappedCode);

        // Start with essential references
        var references = new List<MetadataReference>();
        var referencePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Helper to add reference without duplicates
        void AddReference(string path)
        {
            if (!string.IsNullOrEmpty(path) && referencePaths.Add(path))
            {
                try
                {
                    // Use PortableExecutableReference directly to avoid version conflicts
                    references.Add(PortableExecutableReference.CreateFromFile(path));
                }
                catch (Exception ex)
                {
                    throw new BlakeExecutionException(
                        $"Error creating PortableExecutableReference from file '{path}' at line {line}: {ex.GetType().Name}: {ex.Message}",
                        ex);
                }
            }
        }

        // Add Microsoft.CodeAnalysis.dll reference for the embedded Blake API
        // We find it from already-loaded assemblies since we can't use Assembly.GetExecutingAssembly().Location
        // (it's empty when loaded from NuGet packages)
        Assembly? codeAnalysisAssembly = null;
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            try
            {
                if (asm.GetName().Name == "Microsoft.CodeAnalysis")
                {
                    codeAnalysisAssembly = asm;
                    break;
                }
            }
            catch (NotSupportedException)
            {
                // Dynamic or collectible assemblies don't support GetName()
                continue;
            }
        }

        if (codeAnalysisAssembly != null && !string.IsNullOrEmpty(codeAnalysisAssembly.Location))
        {
            AddReference(codeAnalysisAssembly.Location);
        }
        else
        {
            throw new BlakeExecutionException(
                $"Microsoft.CodeAnalysis.dll not found in loaded assemblies or has empty Location",
                null);
        }

        // FIRST: Add references from the compilation - these are the authoritative references for the target app
        if (_compilation != null)
        {
            foreach (var reference in _compilation.References)
            {
                if (reference is PortableExecutableReference portableRef && !string.IsNullOrEmpty(portableRef.FilePath))
                {
                    // Filter out specific assemblies that have namespace conflicts with Blake.Runtime
                    var fileName = Path.GetFileNameWithoutExtension(portableRef.FilePath);
                    if (fileName != null &&
                        fileName != "Blake.SourceGenerator" &&  // Has "Blake.SourceGenerator" namespace that conflicts with "Blake" class
                        fileName != "Blake.SourceGenerator.Tests")  // Has "Blake.SourceGenerator.Tests" namespace that conflicts with "Blake" class
                    {
                        AddReference(portableRef.FilePath);
                    }
                }
            }
        }
        else
        {
            // When no compilation context (e.g., unit tests), add all runtime assemblies from AppDomain
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    var name = asm.GetName().Name;
                    // Skip specific assemblies that would cause conflicts or that we handle explicitly
                    if (name != null &&
                        !name.StartsWith("Microsoft.CodeAnalysis") &&
                        name != "Blake.SourceGenerator" &&  // Has "Blake.SourceGenerator" namespace that conflicts with "Blake" class
                        name != "Blake.SourceGenerator.Tests" &&  // Has "Blake.SourceGenerator.Tests" namespace that conflicts with "Blake" class
                        name != "Blake.Runtime" &&  // Skip our cached Blake API - we add it explicitly
                        !string.IsNullOrEmpty(asm.Location))
                    {
                        AddReference(asm.Location);
                    }
                }
                catch (NotSupportedException)
                {
                    // Dynamic or collectible assemblies don't support GetName()
                    continue;
                }
            }
        }

        // Add netstandard if available (needed for netstandard2.0 assemblies like Blake.SourceGenerator)
        // Try to find it in the .NET SDK reference assemblies
        // We avoid Assembly.Load to prevent triggering Roslyn version conflicts
        try
        {
            var runtimePath = Path.GetDirectoryName(typeof(object).Assembly.Location);
            if (runtimePath != null)
            {
                var dotnetRoot = Path.GetDirectoryName(Path.GetDirectoryName(runtimePath));
                if (dotnetRoot != null)
                {
                    var netstandardRefPath = Path.Combine(dotnetRoot, "packs", "NETStandard.Library.Ref");
                    if (Directory.Exists(netstandardRefPath))
                    {
                        var versions = Directory.GetDirectories(netstandardRefPath)
                            .Select(d => Path.GetFileName(d))
                            .OrderByDescending(v => v)
                            .FirstOrDefault();

                        if (versions != null)
                        {
                            var netstandardDll = Path.Combine(netstandardRefPath, versions, "ref", "netstandard2.0", "netstandard.dll");
                            AddReference(netstandardDll);
                        }
                    }
                }
            }
        }
        catch (DirectoryNotFoundException)
        {
            // netstandard directory not found - compilation references should be sufficient
        }
        catch (UnauthorizedAccessException)
        {
            // No access to netstandard directory - compilation references should be sufficient
        }

        // Compile Blake API once and add as reference (cached for subsequent meta-blocks)
        EnsureBlakeApiCompiled(references);
        if (_blakeApiAssemblyBytes != null)
        {
            references.Add(MetadataReference.CreateFromImage(_blakeApiAssemblyBytes));
        }

        // Create compilation
        var compilation = CSharpCompilation.Create(
            assemblyName: className,
            syntaxTrees: new[] { syntaxTree },
            references: references,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        // Check for compilation errors
        var diagnostics = compilation.GetDiagnostics();
        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Any())
        {
            var errorMessages = string.Join("\n", errors.Select(e => e.ToString()));
            throw new BlakeExecutionException(
                $"Compilation error in meta-block at line {line}:\n{errorMessages}",
                null);
        }

        // Emit to memory
        using var ms = new MemoryStream();
        var emitResult = compilation.Emit(ms);

        if (!emitResult.Success)
        {
            var failures = emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error);
            var errorMessages = string.Join("\n", failures.Select(f => f.ToString()));
            throw new BlakeExecutionException(
                $"Emit error in meta-block at line {line}:\n{errorMessages}",
                null);
        }

        // Load and execute
        ms.Seek(0, SeekOrigin.Begin);
        var assembly = Assembly.Load(ms.ToArray());
        var type = assembly.GetType(className);
        var method = type?.GetMethod("Execute", BindingFlags.Public | BindingFlags.Static);

        if (method == null)
        {
            throw new BlakeExecutionException(
                $"Could not find Execute method in generated assembly at line {line}",
                null);
        }

        var result = method.Invoke(null, new object?[] { _compilation });
        return result?.ToString() ?? string.Empty;
    }

    /// <summary>
    /// Loads embedded resource file as string.
    /// </summary>
    private static string LoadEmbeddedResource(string resourceName)
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(resourceName);
        if (stream == null)
        {
            throw new InvalidOperationException($"Embedded resource '{resourceName}' not found");
        }
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    /// <summary>
    /// Builds a C# interpolated string from a quasi-quote.
    /// `public @(type) @(name) { get; set; }` becomes $"public {type} {name} {{ get; set; }}\n"
    /// Note: A newline is automatically appended after block quasi-quotes (not inline ones).
    /// </summary>
    private string BuildInterpolatedString(QuasiQuote qq)
    {
        var sb = new StringBuilder();
        sb.Append("$\"");

        bool isFirst = true;
        foreach (var part in qq.Parts)
        {
            switch (part)
            {
                case QuasiQuoteText text:
                    var content = text.Text;

                    if (isFirst && content.Length > 0 && char.IsWhiteSpace(content[0]))
                    {
                        content = " " + content;
                    }

                    var escaped = content
                        .Replace("\\", "\\\\")
                        .Replace("\r\n", "\\n")
                        .Replace("\n", "\\n")
                        .Replace("\r", "\\n")
                        .Replace("\"", "\\\"")
                        .Replace("{", "{{")
                        .Replace("}", "}}");
                    sb.Append(escaped);
                    break;

                case QuasiQuoteSplice splice:
                    sb.Append('{');
                    sb.Append(splice.Expression);
                    sb.Append('}');
                    break;
            }
            isFirst = false;
        }

        // Implicit newline after block quasi-quotes (not inline)
        if (!qq.IsInline)
        {
            sb.Append("\\n");
        }
        sb.Append('"');
        return sb.ToString();
    }

    /// <summary>
    /// Applies ordered transformations to complete C# source code.
    /// This is an extensible pipeline - additional transformations can be added here.
    /// </summary>
    private string ApplyTransformations(string completeSource)
    {
        var code = completeSource;

        // Transformation 1: Infer var return types
        code = ReturnTypeInference.ApplyTransformation(code, _compilation);

        // Future transformations can be added here
        // code = TransformSomethingElse(code);

        return code;
    }
}
